# .github/workflows/terraform.yml

name: Terraform Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy_infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    outputs:
      # Output the Terraform plan file path for other jobs to use
      values: ${{ steps.set_plan.outputs.values }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        run: az login

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: set_plan
        run: terraform plan -out=tfplan

      - name: Set Outputs
        id: set_outputs
        run: echo "::set-output name=values::./tfplan"

      - name: Terraform Apply
        run: terraform apply -auto-approve

  destroy_infra:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    needs: [deploy_infra]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        run: az login

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=./tfplan
